version: '3.7'
services:
  workflow_project:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    environment:
      MODE: development
    volumes:
    - '.:/app'
    - '/app/node_modules/'
    command: /bin/sh -c "yarn serve"
